version: '3.9'
services:
  jenkins:
    container_name: jenkins
    build:
      context: .
    volumes:
      - '$PWD/jenkins-data:/var/jenkins_home'
      - '$PWD/jenkins-docker-certs:/certs/client:ro'
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST='tcp://docker:2376'
      - DOCKER_CERT_PATH='/certs/client'
      - DOCKER_TLS_VERIFY=1
    networks:
      - jenkins
networks:
  jenkins:
